services:
  nats-server:
    image: nats:latest
    # ports:
    #   - "8222:8222"

  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: client-gateway-prod
    ports:
      - "${CLIENT_GATEWAY_PORT}:3000"
    # volumes:
    #   - ./client-gateway/src:/usr/src/app/src
    # command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222

  products-ms:
    build: 
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: products-ms-prod
    # volumes:
    #   - ./products-ms/src:/usr/src/app/src
    # command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  # Orders MS
  orders-ms:
    build: 
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_MS_DB=${ORDERS_MS_DB}
    image: orders-ms-prod
    # volumes:
    #   - ./orders-ms/src:/usr/src/app/src
    # command: npm run start:dev
    environment:
      - PORT=3002
      # - DATABASE_URL=postgresql://postgres:123456@orders-db:5432/ordersdb?schema=public
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_MS_DB}

  # # Orders DB
  # orders-db:
  #   container_name: orders_database
  #   image: postgres:16.2
  #   restart: always
  #   volumes:
  #     - ./orders-ms/postgres:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=123456
  #     - POSTGRES_DB=ordersdb

  # Payment-ms
  payment-ms:
    build: 
      context: ./payment-ms
      dockerfile: dockerfile.prod
    image: payment-ms-prod
    # volumes:
    #   - ./payment-ms/src:/usr/src/app/src
    ports:
      - ${PAYMENT_MS_PORT}:${PAYMENT_MS_PORT}
    # command: npm run start:dev
    environment:
      - PORT=${PAYMENT_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - ENDPOINT_SECRET=${ENDPOINT_SECRET}
      - SUCCESS_URL=${SUCCESS_URL}
      - CANCEL_URL=${CANCEL_URL}

  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: auth-ms-prod
    # volumes:
    #   - ./auth-ms/src:/usr/src/app/src
    # ports:
    #   - ${AUTH_MS_PORT}:${AUTH_MS_PORT}
    # command: npm run start:dev
    environment:
      - PORT=${AUTH_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${MONGODB_CONNECTION}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
